### ISSUE TITLE
Add CMake support. Project layout

### ISSUE THREAD

**Issue by Manu343726** [Manu343726/ctti#7]
A global `CMakeLists.txt` for development would be great, plus a hierarchy of examples and tests.

**Comment by foonathan** [comment]
As long as it is not required to use this library, I agree. It is a header only library and doesn't need stuff such as my compatibility lib.

**Comment by Manu343726** [comment]
Is just to make the development setup easier. I'm currently maintaining one different IDE project in each local copy I have... I agree, this should be header only and not require any setup.

**Comment by Manu343726** [comment]
Prior to writing the `CMakeLists.txt` file I would like to talk about project layout. I had something similar to this in mind:

 - `CMakeLists.txt` at root with project settings.
 - `include` folder, so we have `include/ctti/` where the last is the current `ctti` folder. 
 - `tests`: I would like to write tests of two kinds, to check for `constexpr` evaluation, and to check for correct results. `static_assert()` should do the work.
 - `examples`: Examples of ctti usage. Also including assembly listings from different compilers would be helpful. Also a cmake option to enable assembly output when building examples would be great, I hate the MSVC cli.

**Comment by foonathan** [comment]
Sounds alright.
